1337x:
  url: '1337x.org\/torrent\/(\d*)'
  css: div.torrentInfoBtn a.torrentDw
  
vertor:
  url: 'vertor.com\/torrents\/(\d*)\/(.*)'
  xpath: /html/body/div[4]/div[2]/ul/li[2]/a[2]
  offset: 1

h33t:
  url: 'h33t.com\/details\.php\?id=(\w*)'

kickass:
  url: 'kat.ph\/([\w-]*).html([\/]?)'
